<?php

/** @generate-class-entries */

// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

namespace Kiosk;

class Bridge {

    public function __construct() {}

    public function resolveCoords(string $location): array {}

    public function fetchWeather(float $lat, float $lon): array {}

    public function fetchTolls(): array {}

    public function mercureSubscriptions(): array {}

    public function mercurePublish(string $topic, string $data, string $updateType, string $id): array {}

}


