package ext

// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

// #include <stdlib.h>
// #include "kiosk.h"
import "C"
import (
	_ "runtime/cgo"
	"unsafe"

	"github.com/dunglas/frankenphp"
)

func init() {
	frankenphp.RegisterExtension(unsafe.Pointer(&C.kiosk_module_entry))
}

//export go_kiosk_resolve_coords
func go_kiosk_resolve_coords(location *C.zend_string) unsafe.Pointer {
	return kiosk_resolve_coords(location)
}

//export go_kiosk_fetch_weather
func go_kiosk_fetch_weather(lat float64, lon float64) unsafe.Pointer {
	return kiosk_fetch_weather(lat, lon)
}

//export go_kiosk_fetch_tolls
func go_kiosk_fetch_tolls() unsafe.Pointer {
	return kiosk_fetch_tolls()
}

//export go_kiosk_mercure_subscriptions
func go_kiosk_mercure_subscriptions() unsafe.Pointer {
	return kiosk_mercure_subscriptions()
}

//export go_kiosk_mercure_publish
func go_kiosk_mercure_publish(topic *C.zend_string, data *C.zend_string, typ *C.zend_string, id *C.zend_string) unsafe.Pointer {
	return kiosk_mercure_publish(topic, data, typ, id)
}
