<?php

/** @generate-class-entries */

// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

function kiosk_resolve_coords(string $location): array {}

function kiosk_fetch_weather(float $lat, float $lon): array {}

function kiosk_fetch_tolls(): array {}

function kiosk_mercure_subscriptions(): array {}

function kiosk_mercure_publish(string $topic, string $data, string $type, string $id): array {}


