package ext

// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

// #include <stdlib.h>
// #include "kiosk.h"
import "C"
import (
	"runtime/cgo"
	"unsafe"

	"github.com/dunglas/frankenphp"
)

func init() {
	frankenphp.RegisterExtension(unsafe.Pointer(&C.kiosk_module_entry))
}

//export registerGoObject
func registerGoObject(obj interface{}) C.uintptr_t {
	handle := cgo.NewHandle(obj)
	return C.uintptr_t(handle)
}

//export getGoObject
func getGoObject(handle C.uintptr_t) interface{} {
	h := cgo.Handle(handle)
	return h.Value()
}

//export removeGoObject
func removeGoObject(handle C.uintptr_t) {
	h := cgo.Handle(handle)
	h.Delete()
}

//export create_Bridge_object
func create_Bridge_object() C.uintptr_t {
	obj := &Bridge{}
	return registerGoObject(obj)
}

//export resolveCoords_wrapper
func resolveCoords_wrapper(handle C.uintptr_t, location *C.zend_string) unsafe.Pointer {
	obj := getGoObject(handle)
	if obj == nil {
		return nil
	}
	structObj := obj.(*Bridge)
	return structObj.ResolveCoords(location)
}

//export fetchWeather_wrapper
func fetchWeather_wrapper(handle C.uintptr_t, lat float64, lon float64) unsafe.Pointer {
	obj := getGoObject(handle)
	if obj == nil {
		return nil
	}
	structObj := obj.(*Bridge)
	return structObj.FetchWeather(lat, lon)
}

//export fetchTolls_wrapper
func fetchTolls_wrapper(handle C.uintptr_t) unsafe.Pointer {
	obj := getGoObject(handle)
	if obj == nil {
		return nil
	}
	structObj := obj.(*Bridge)
	return structObj.FetchTolls()
}

//export mercureSubscriptions_wrapper
func mercureSubscriptions_wrapper(handle C.uintptr_t) unsafe.Pointer {
	obj := getGoObject(handle)
	if obj == nil {
		return nil
	}
	structObj := obj.(*Bridge)
	return structObj.MercureSubscriptions()
}

//export mercurePublish_wrapper
func mercurePublish_wrapper(handle C.uintptr_t, topic *C.zend_string, data *C.zend_string, updateType *C.zend_string, id *C.zend_string) unsafe.Pointer {
	obj := getGoObject(handle)
	if obj == nil {
		return nil
	}
	structObj := obj.(*Bridge)
	return structObj.MercurePublish(topic, data, updateType, id)
}
